# This workflow runs the test project.
name: .Net Test

# Controls the event triggering the workflow
on:
  # Triggers the workflow whenever changes are pushed on one of the specified branch.
  push:
    branches:
      - master
      - develop
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
  # Gives the possibility to trigger the workflow from another workflow.
  workflow_call:

jobs:
  # Build the Solution & Test it
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    # Check-out the branch
    - name: Check-out Branch
      uses: actions/checkout@v3
    # Setup the .Net environment
    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    # Build the solution
    - name : Build Solution
      run: dotnet build --configuration Release
    # Runs the unit tests
    - name : Test Project
      run: dotnet test --verbosity normal
